name: PowerShell Publisher
description: Publish a PowerShell script or module to a repository
inputs:
  Package:
    description: Path to the .ps1, .psd1, or .psm1 file.
    required: true
  TargetRepoUri:
    description: Uri to the modules feed of the repository.
    required: true
  NuGetApiToken:
    description: API key for the repository
    required: true
  Token:
    description: GitHub Token with access to this repo
    required: True
runs:
  using: "docker"
  image: Dockerfile
  env:
    Package: ${{ inputs.Package }}
    TargetRepoUri: ${{ inputs.TargetRepoUri }}
    NugetApiKey: ${{ inputs.NuGetApiToken }}
    GitHub_Token: ${{ inputs.Token }}
