name: PowerShell Publisher
description: Publish a PowerShell script or module to a repository
inputs:
  entrypoint:
    description: Path to the .ps1, .psd1, or .psm1 file.
    required: true
  repoModule:
    description: Uri to the modules feed of the repository.
    required: true
  repoScript:
    description: Uri to the scripts feed of the repository.
    required: true
  apikey:
    description: API key for the repository; typically ${{ secrets.RepoKey }}
    required: true
runs:
  using: "docker"
  image: Dockerfile
  args:
  - ${{ inputs.entrypoint }}
  - ${{ inputs.repoModule }}
  - ${{ inputs.repoScript }}
  - ${{ inputs.apikey }}
